/**
 * Tokens de inyección de dependencias para repositorios
 * Según el principio DIP (Dependency Inversion Principle)
 */

// Repositorios
export const USUARIO_REPOSITORY = Symbol('USUARIO_REPOSITORY');
export const LOTE_REPOSITORY = Symbol('LOTE_REPOSITORY');
export const TANDA_REPOSITORY = Symbol('TANDA_REPOSITORY');
export const VENTA_REPOSITORY = Symbol('VENTA_REPOSITORY');
export const VENTA_MAYOR_REPOSITORY = Symbol('VENTA_MAYOR_REPOSITORY');
export const CUADRE_REPOSITORY = Symbol('CUADRE_REPOSITORY');
export const CUADRE_MAYOR_REPOSITORY = Symbol('CUADRE_MAYOR_REPOSITORY');
export const MINI_CUADRE_REPOSITORY = Symbol('MINI_CUADRE_REPOSITORY');
export const EQUIPAMIENTO_REPOSITORY = Symbol('EQUIPAMIENTO_REPOSITORY');
export const FONDO_RECOMPENSAS_REPOSITORY = Symbol('FONDO_RECOMPENSAS_REPOSITORY');
export const NOTIFICACION_REPOSITORY = Symbol('NOTIFICACION_REPOSITORY');
export const PEDIDO_STOCK_REPOSITORY = Symbol('PEDIDO_STOCK_REPOSITORY');
export const CONFIGURACION_REPOSITORY = Symbol('CONFIGURACION_REPOSITORY');
export const TIPO_INSUMO_REPOSITORY = Symbol('TIPO_INSUMO_REPOSITORY');
export const STOCK_ADMIN_REPOSITORY = Symbol('STOCK_ADMIN_REPOSITORY');
export const AUDIT_LOG_REPOSITORY = Symbol('AUDIT_LOG_REPOSITORY');
export const EVENT_STORE_REPOSITORY = Symbol('EVENT_STORE_REPOSITORY');
export const OUTBOX_REPOSITORY = Symbol('OUTBOX_REPOSITORY');
export const TOKEN_BLACKLIST_REPOSITORY = Symbol('TOKEN_BLACKLIST_REPOSITORY');
export const IDEMPOTENCY_KEY_REPOSITORY = Symbol('IDEMPOTENCY_KEY_REPOSITORY');

// Servicios de dominio
export const CALCULADORA_INVERSION_SERVICE = Symbol('CALCULADORA_INVERSION_SERVICE');
export const CALCULADORA_TANDAS_SERVICE = Symbol('CALCULADORA_TANDAS_SERVICE');
export const CALCULADORA_GANANCIAS_SERVICE = Symbol('CALCULADORA_GANANCIAS_SERVICE');

// Servicios de infraestructura
export const CACHE_SERVICE = Symbol('CACHE_SERVICE');
export const NOTIFICATION_DISPATCHER = Symbol('NOTIFICATION_DISPATCHER');
export const EVENT_BUS_SERVICE = Symbol('EVENT_BUS_SERVICE');

// Unit of Work
export const UNIT_OF_WORK = Symbol('UNIT_OF_WORK');
